name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_COMMIT: ${{ contains(github.event.commits.*.message, '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !env.SKIP_COMMIT }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !env.SKIP_COMMIT }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: v

  discord_notify:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - name: Discord notification
        if: ${{ always() && github.ref_name == 'main' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          status: ${{ job.status }}
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
          title: ${{ job.status == 'success' && 'A new version deployed' || 'Build failed!' }}
          description: |
            **Commit:** [${{ github.sha }}](${{ github.event.head_commit.url }})  
            **Author:** ${{ github.event.head_commit.author.name }}  
            **Message:** ${{ github.event.head_commit.message }}
